apisix:
  allow_admin:
    - 0.0.0.0/0
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin
etcd:
   host:
     - http://etcd:2379
   prefix: "/apisix"
   timeout: 30
ext-plugin:
  path_for_test: /tmp/runner.sock
nginx_config:
  user: root
